# Generated by Django 4.0.3 on 2022-06-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_rename_data_de_nascimento_aluno_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
